name: build

on:
<<<<<<< HEAD
  pull_request_target:
    branches: [main]
  workflow_dispatch:
=======
  pull_request:
    branches: [main]
>>>>>>> parent of bfc93611 (Update build.yml)
  push: 
    branches:
      - '*/*'
      - '!main'

jobs:
  workflow-build:
    uses: ./.github/workflows/workflow-build.yml