name: build

on:
  pull_request_target:
    branches: [main]
  workflow_dispatch:
  push: 
    branches:
      - '*/*'
      - '!main'

jobs:
  workflow-build:
    uses: ./.github/workflows/workflow-build.yml
